"use client"

import { Brain, ShieldCheck, Sparkles } from "lucide-react"
import { type AgreementWithDetails } from "@/lib/api/agreements"

interface AIBadgeProps {
  agreement: AgreementWithDetails
  variant?: "badge" | "compact" | "detailed"
}

export function AIBadge({ agreement, variant = "badge" }: AIBadgeProps) {
  const isAIGenerated = agreement.agreement_source === "groq_llama"
  const isDeterministic = agreement.agreement_source === "deterministic_template"
  const metadata = agreement.generation_metadata || {}

  if (!isAIGenerated && !isDeterministic) return null

  // ── Deterministic template (current) ──────────────────────────────────────
  // The agreement body is template-generated (no LLM), so financial terms can
  // never be hallucinated. The plain-English brief shown to the tenant is the
  // only AI-generated part.
  if (isDeterministic) {
    if (variant === "compact") {
      return (
        <div className="flex items-center gap-1.5 px-2 py-1 bg-gradient-to-r from-emerald-50 to-green-50 rounded-full border border-emerald-200">
          <ShieldCheck className="w-3 h-3 text-emerald-600" />
          <span className="text-xs font-medium text-emerald-700">Verified Template</span>
        </div>
      )
    }

    if (variant === "badge") {
      return (
        <div className="flex items-center gap-2 p-2.5 bg-gradient-to-r from-emerald-50 to-green-50 rounded-lg border border-emerald-200">
          <div className="w-5 h-5 bg-gradient-to-r from-emerald-500 to-green-500 rounded-full flex items-center justify-center flex-shrink-0">
            <ShieldCheck className="w-3 h-3 text-white" />
          </div>
          <div className="flex-1 min-w-0">
            <p className="text-xs font-semibold text-emerald-800">Verified Legal Template</p>
            <p className="text-xs text-emerald-600">
              Deterministic terms • AI plain-English brief
            </p>
          </div>
        </div>
      )
    }

    return (
      <div className="p-4 bg-gradient-to-r from-emerald-50 to-green-50 rounded-xl border border-emerald-200">
        <div className="flex items-start gap-3">
          <div className="w-8 h-8 bg-gradient-to-r from-emerald-500 to-green-500 rounded-full flex items-center justify-center flex-shrink-0">
            <ShieldCheck className="w-4 h-4 text-white" />
          </div>
          <div className="flex-1 min-w-0">
            <p className="text-sm font-semibold text-emerald-800 mb-2">Verified Legal Template</p>
            <p className="text-xs text-emerald-700 leading-relaxed">
              This agreement was produced by NuloAfrica&apos;s deterministic legal template.
              All financial figures (rent, deposit, fees) are filled directly from the listing
              and platform policy — never generated by an AI model — so they cannot be
              hallucinated. The plain-English summary above is AI-generated for convenience.
            </p>
            {metadata.template_version && (
              <p className="text-[11px] text-emerald-500 mt-2 font-mono">
                Template: {metadata.template_version}
              </p>
            )}
          </div>
        </div>
      </div>
    )
  }

  // ── Legacy AI-generated (groq_llama) ──────────────────────────────────────

  // Compact version - just shows AI indicator
  if (variant === "compact") {
    return (
      <div className="flex items-center gap-1.5 px-2 py-1 bg-gradient-to-r from-blue-50 to-purple-50 rounded-full border border-blue-200">
        <Sparkles className="w-3 h-3 text-blue-600" />
        <span className="text-xs font-medium text-blue-700">AI-Enhanced</span>
      </div>
    )
  }

  // Badge version - shows in card header
  if (variant === "badge") {
    return (
      <div className="flex items-center gap-2 p-2.5 bg-gradient-to-r from-blue-50 to-purple-50 rounded-lg border border-blue-200">
        <div className="w-5 h-5 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full flex items-center justify-center flex-shrink-0">
          <Brain className="w-3 h-3 text-white" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-xs font-semibold text-blue-800">AI-Enhanced Agreement</p>
          <p className="text-xs text-blue-600">
            {metadata.compliance_score ? `${metadata.compliance_score.toFixed(0)}% compliance` : 'High compliance'} • Professional quality
          </p>
        </div>
      </div>
    )
  }

  // Detailed version - shows full metadata
  return (
    <div className="p-4 bg-gradient-to-r from-blue-50 to-purple-50 rounded-xl border border-blue-200">
      <div className="flex items-start gap-3">
        <div className="w-8 h-8 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full flex items-center justify-center flex-shrink-0">
          <Brain className="w-4 h-4 text-white" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-sm font-semibold text-blue-800 mb-2">AI-Enhanced Agreement</p>
          
          <div className="grid grid-cols-2 gap-3 text-xs">
            {metadata.compliance_score && (
              <div>
                <p className="text-blue-600 font-medium">Compliance Score</p>
                <p className="text-blue-800 font-semibold">{metadata.compliance_score.toFixed(1)}%</p>
              </div>
            )}
            
            {metadata.tokens_used && (
              <div>
                <p className="text-blue-600 font-medium">Quality Score</p>
                <p className="text-blue-800 font-semibold">Professional</p>
              </div>
            )}
            
            {metadata.model_used && (
              <div>
                <p className="text-blue-600 font-medium">Generated With</p>
                <p className="text-blue-800 font-semibold">Advanced AI</p>
              </div>
            )}
            
            <div>
              <p className="text-blue-600 font-medium">Enhanced</p>
              <p className="text-blue-800 font-semibold">Legal Quality</p>
            </div>
          </div>
          
          <p className="text-xs text-blue-600 mt-3 italic">
            This agreement was enhanced with artificial intelligence to provide comprehensive legal coverage and professional quality.
          </p>
        </div>
      </div>
    </div>
  )
}
