// Generated by Supabase CLI
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          phone_number: string | null
          password_hash: string | null
          full_name: string | null
          avatar_url: string | null
          trust_score: number | null
          verification_status: string | null
          user_type: 'admin' | 'landlord' | 'tenant'
          last_login_at: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
          phone_verified: boolean | null
          location: string | null
          onboarding_completed: boolean | null
          first_name: string | null
          last_name: string | null
          email_verified: boolean | null
          onboarding_step: number | null
          auth_provider: string | null
          provider_id: string | null
        }
        Insert: {
          id: string
          email: string
          phone_number?: string | null
          password_hash?: string | null
          full_name?: string | null
          avatar_url?: string | null
          trust_score?: number | null
          verification_status?: string | null
          user_type: 'admin' | 'landlord' | 'tenant'
          last_login_at?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
          phone_verified?: boolean | null
          location?: string | null
          onboarding_completed?: boolean | null
          first_name?: string | null
          last_name?: string | null
          email_verified?: boolean | null
          onboarding_step?: number | null
          auth_provider?: string | null
          provider_id?: string | null
        }
        Update: {
          id?: string
          email?: string
          phone_number?: string | null
          password_hash?: string | null
          full_name?: string | null
          avatar_url?: string | null
          trust_score?: number | null
          verification_status?: string | null
          user_type?: 'admin' | 'landlord' | 'tenant'
          last_login_at?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
          phone_verified?: boolean | null
          location?: string | null
          onboarding_completed?: boolean | null
          first_name?: string | null
          last_name?: string | null
          email_verified?: boolean | null
          onboarding_step?: number | null
          auth_provider?: string | null
          provider_id?: string | null
        }
      }
      tenant_profiles: {
        Row: {
          id: string
          employment_status: string | null
          company_name: string | null
          job_title: string | null
          monthly_income_range: string | null
          income_proof_url: string | null
          income_proof_verified: boolean | null
          preferred_property_types: Json | null
          preferred_locations: Json | null
          budget_range: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          employment_status?: string | null
          company_name?: string | null
          job_title?: string | null
          monthly_income_range?: string | null
          income_proof_url?: string | null
          income_proof_verified?: boolean | null
          preferred_property_types?: Json | null
          preferred_locations?: Json | null
          budget_range?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          employment_status?: string | null
          company_name?: string | null
          job_title?: string | null
          monthly_income_range?: string | null
          income_proof_url?: string | null
          income_proof_verified?: boolean | null
          preferred_property_types?: Json | null
          preferred_locations?: Json | null
          budget_range?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      landlord_profiles: {
        Row: {
          id: string
          account_type: string | null
          date_of_birth: string | null
          nin: string | null
          bvn: string | null
          nin_verified: boolean | null
          bvn_verified: boolean | null
          company_name: string | null
          cac_number: string | null
          tax_id: string | null
          owns_properties: boolean | null
          number_of_properties: number | null
          property_addresses: Json | null
          property_documents: Json | null
          id_document_url: string | null
          selfie_photo_url: string | null
          proof_of_address_url: string | null
          bank_statement_url: string | null
          cac_certificate_url: string | null
          tax_clearance_url: string | null
          bank_account_number: string | null
          bank_name: string | null
          account_name: string | null
          payment_method_verified: boolean | null
          verification_fee_paid: boolean | null
          verification_fee_amount: number | null
          verification_fee_paid_at: string | null
          verification_fee_reference: string | null
          verification_submitted_at: string | null
          verification_reviewed_at: string | null
          reviewed_by: string | null
          rejection_reason: string | null
          admin_notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          account_type?: string | null
          date_of_birth?: string | null
          nin?: string | null
          bvn?: string | null
          nin_verified?: boolean | null
          bvn_verified?: boolean | null
          company_name?: string | null
          cac_number?: string | null
          tax_id?: string | null
          owns_properties?: boolean | null
          number_of_properties?: number | null
          property_addresses?: Json | null
          property_documents?: Json | null
          id_document_url?: string | null
          selfie_photo_url?: string | null
          proof_of_address_url?: string | null
          bank_statement_url?: string | null
          cac_certificate_url?: string | null
          tax_clearance_url?: string | null
          bank_account_number?: string | null
          bank_name?: string | null
          account_name?: string | null
          payment_method_verified?: boolean | null
          verification_fee_paid?: boolean | null
          verification_fee_amount?: number | null
          verification_fee_paid_at?: string | null
          verification_fee_reference?: string | null
          verification_submitted_at?: string | null
          verification_reviewed_at?: string | null
          reviewed_by?: string | null
          rejection_reason?: string | null
          admin_notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          account_type?: string | null
          date_of_birth?: string | null
          nin?: string | null
          bvn?: string | null
          nin_verified?: boolean | null
          bvn_verified?: boolean | null
          company_name?: string | null
          cac_number?: string | null
          tax_id?: string | null
          owns_properties?: boolean | null
          number_of_properties?: number | null
          property_addresses?: Json | null
          property_documents?: Json | null
          id_document_url?: string | null
          selfie_photo_url?: string | null
          proof_of_address_url?: string | null
          bank_statement_url?: string | null
          cac_certificate_url?: string | null
          tax_clearance_url?: string | null
          bank_account_number?: string | null
          bank_name?: string | null
          account_name?: string | null
          payment_method_verified?: boolean | null
          verification_fee_paid?: boolean | null
          verification_fee_amount?: number | null
          verification_fee_paid_at?: string | null
          verification_fee_reference?: string | null
          verification_submitted_at?: string | null
          verification_reviewed_at?: string | null
          reviewed_by?: string | null
          rejection_reason?: string | null
          admin_notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      admins: {
        Row: {
          id: string
          role_level: number | null
          permissions: Json | null
          last_action_at: string | null
          created_at: string
          admin_code: string | null
          updated_at: string
        }
        Insert: {
          id: string
          role_level?: number | null
          permissions?: Json | null
          last_action_at?: string | null
          created_at?: string
          admin_code?: string | null
          updated_at?: string
        }
        Update: {
          id?: string
          role_level?: number | null
          permissions?: Json | null
          last_action_at?: string | null
          created_at?: string
          admin_code?: string | null
          updated_at?: string
        }
      }
      admin_codes: {
        Row: {
          id: string
          code: string
          description: string | null
          is_active: boolean | null
          max_uses: number | null
          current_uses: number | null
          expires_at: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          code: string
          description?: string | null
          is_active?: boolean | null
          max_uses?: number | null
          current_uses?: number | null
          expires_at?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          code?: string
          description?: string | null
          is_active?: boolean | null
          max_uses?: number | null
          current_uses?: number | null
          expires_at?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      onboarding_progress: {
        Row: {
          id: string
          user_id: string | null
          user_type: string
          step_name: string
          step_number: number
          completed: boolean | null
          data: Json | null
          completed_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          user_type: string
          step_name: string
          step_number: number
          completed?: boolean | null
          data?: Json | null
          completed_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          user_type?: string
          step_name?: string
          step_number?: number
          completed?: boolean | null
          data?: Json | null
          completed_at?: string | null
          created_at?: string
        }
      }
      phone_verifications: {
        Row: {
          id: string
          phone_number: string
          otp_code: string
          attempts: number | null
          expires_at: string | null
          verified: boolean | null
          created_at: string
        }
        Insert: {
          id?: string
          phone_number: string
          otp_code: string
          attempts?: number | null
          expires_at?: string | null
          verified?: boolean | null
          created_at?: string
        }
        Update: {
          id?: string
          phone_number?: string
          otp_code?: string
          attempts?: number | null
          expires_at?: string | null
          verified?: boolean | null
          created_at?: string
        }
      }
      verification_documents: {
        Row: {
          id: string
          user_id: string | null
          document_type: string
          document_url: string
          document_name: string | null
          file_size: number | null
          mime_type: string | null
          uploaded_at: string | null
          verified_at: string | null
          verification_status: string | null
          verification_notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          document_type: string
          document_url: string
          document_name?: string | null
          file_size?: number | null
          mime_type?: string | null
          uploaded_at?: string | null
          verified_at?: string | null
          verification_status?: string | null
          verification_notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          document_type?: string
          document_url?: string
          document_name?: string | null
          file_size?: number | null
          mime_type?: string | null
          uploaded_at?: string | null
          verified_at?: string | null
          verification_status?: string | null
          verification_notes?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// User type definitions
export type User = Database['public']['Tables']['users']['Row']
export type UserInsert = Database['public']['Tables']['users']['Insert']
export type UserUpdate = Database['public']['Tables']['users']['Update']

export type TenantProfile = Database['public']['Tables']['tenant_profiles']['Row']
export type TenantProfileInsert = Database['public']['Tables']['tenant_profiles']['Insert']
export type TenantProfileUpdate = Database['public']['Tables']['tenant_profiles']['Update']

export type LandlordProfile = Database['public']['Tables']['landlord_profiles']['Row']
export type LandlordProfileInsert = Database['public']['Tables']['landlord_profiles']['Insert']
export type LandlordProfileUpdate = Database['public']['Tables']['landlord_profiles']['Update']

export type Admin = Database['public']['Tables']['admins']['Row']
export type AdminInsert = Database['public']['Tables']['admins']['Insert']
export type AdminUpdate = Database['public']['Tables']['admins']['Update']

export type OnboardingProgress = Database['public']['Tables']['onboarding_progress']['Row']
export type OnboardingProgressInsert = Database['public']['Tables']['onboarding_progress']['Insert']
export type OnboardingProgressUpdate = Database['public']['Tables']['onboarding_progress']['Update']

export type PhoneVerification = Database['public']['Tables']['phone_verifications']['Row']
export type PhoneVerificationInsert = Database['public']['Tables']['phone_verifications']['Insert']
export type PhoneVerificationUpdate = Database['public']['Tables']['phone_verifications']['Update']

// Auth context types
export interface AuthUser {
  user: User | null
  profile: TenantProfile | LandlordProfile | Admin | null
  loading: boolean
  error: string | null
}

export interface AuthContextType extends AuthUser {
  signUp: (email: string, password: string, metadata: any) => Promise<any>
  signIn: (email: string, password: string) => Promise<any>
  signInWithGoogle: () => Promise<any>
  signOut: () => Promise<void>
  resetPassword: (email: string) => Promise<any>
  updateProfile: (updates: any) => Promise<any>
  refreshUser: () => Promise<void>
}

// Route types
export type UserRole = 'admin' | 'tenant' | 'landlord'
export type AuthStatus = 'loading' | 'authenticated' | 'unauthenticated' | 'error'
